---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present
  - name: start the httpd service
    service:
      name: httpd
      state: started
    